CREATE DATABASE IF NOT EXISTS `PRODUCTS` DEFAULT CHARACTER SET UTF8MB4 COLLATE utf8_general_ci;
USE `PRODUCTS`;

CREATE TABLE `APPARTENIR2` (
  `id` VARCHAR(42),
  `id_1` VARCHAR(42),
  PRIMARY KEY (`id`, `id_1`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `CARTS` (
  `id` VARCHAR(42),
  `quantity` VARCHAR(42),
  `id_1` VARCHAR(42),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `CATEGORIES` (
  `id` VARCHAR(42),
  `name` VARCHAR(42),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `CONTENIR1` (
  `id` VARCHAR(42),
  `id_1` VARCHAR(42),
  PRIMARY KEY (`id`, `id_1`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `IMAGES` (
  `id` VARCHAR(42),
  `name` VARCHAR(42),
  `url` VARCHAR(42),
  `id_1` VARCHAR(42),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `ORDERS` (
  `id` VARCHAR(42),
  `quantity` VARCHAR(42),
  `date` VARCHAR(42),
  `id_1` VARCHAR(42),
  `id_2` VARCHAR(42),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `PACKAGE_SIZES` (
  `id` VARCHAR(42),
  `name` VARCHAR(42),
  `id_1` VARCHAR(42),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `PRODUCTS` (
  `id` VARCHAR(42),
  `name` VARCHAR(42),
  `category` VARCHAR(42),
  `price` VARCHAR(42),
  `quantity_in_stock` VARCHAR(42),
  `favorite` VARCHAR(42),
  `date_added` VARCHAR(42),
  `id_1` VARCHAR(42),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `USERS` (
  `id` VARCHAR(42),
  `first_name` VARCHAR(42),
  `last_name` VARCHAR(42),
  `email` VARCHAR(42),
  `password` VARCHAR(42),
  `date_registered` VARCHAR(42),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE `APPARTENIR2` ADD FOREIGN KEY (`id_1`) REFERENCES `ORDERS` (`id`);
ALTER TABLE `APPARTENIR2` ADD FOREIGN KEY (`id`) REFERENCES `PRODUCTS` (`id`);
ALTER TABLE `CARTS` ADD FOREIGN KEY (`id_1`) REFERENCES `USERS` (`id`);
ALTER TABLE `CONTENIR1` ADD FOREIGN KEY (`id_1`) REFERENCES `CARTS` (`id`);
ALTER TABLE `CONTENIR1` ADD FOREIGN KEY (`id`) REFERENCES `PRODUCTS` (`id`);
ALTER TABLE `IMAGES` ADD FOREIGN KEY (`id_1`) REFERENCES `PRODUCTS` (`id`);
ALTER TABLE `ORDERS` ADD FOREIGN KEY (`id_2`) REFERENCES `USERS` (`id`);
ALTER TABLE `ORDERS` ADD FOREIGN KEY (`id_1`) REFERENCES `PACKAGE_SIZES` (`id`);
ALTER TABLE `PACKAGE_SIZES` ADD FOREIGN KEY (`id_1`) REFERENCES `PRODUCTS` (`id`);
ALTER TABLE `PRODUCTS` ADD FOREIGN KEY (`id_1`) REFERENCES `CATEGORIES` (`id`);